<a href="https://colab.research.google.com/github/sirrengaw/python/blob/main/Desafio_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Desafio 03
#Nivel Facil

"""
a.	leia do teclado as dimensões de um retângulo (base e altura), 
calcular e escrever a área do retângulo. (Valores inválidos: 0 e números negativos).
"""
from google.colab import output
x = 0;
while x != 1 :
  base = float(input("Entre com o valor em metros da base do retângulo: "))
  if base <= 0:
    output.clear()
    print("*** Erro! Digite um numero maior que ZERO! ***")
  else:
    x = 1;
x = 0;
while x != 1 :
  altura = float(input("Entre com o valor em metros da altura do retângulo: "))
  if altura <= 0:
    output.clear()
    print("*** Erro! Digite um numero maior que ZERO! ***")
  else:
    x = 1;
area = (base * altura) / 2
print("=====================================================================")
print("A área do triangulo é %.2f" % area,"m2")
print("=====================================================================")

*** Erro! Digite um numero maior que ZERO! ***
Entre com o valor em metros da base do retângulo: 10
Entre com o valor em metros da altura do retângulo: 10
=====================================================================
A área do triangulo é 50.00 m2
=====================================================================

In [ ]:
"""
b.	leia do teclado o número total de eleitores de um município, o número de 
votos brancos, nulos e válidos. Calcular e escrever o percentual que cada um 
representa em relação ao total de eleitores. 
(Valores inválidos: números negativos).
"""
from google.colab import output
x = 0;
while x != 1 :
  brancos = float(input("Entre com o valor dos votos BRANCOS: "))
  if brancos < 0:
    output.clear()
    print("*** Erro! Digite um numero maior ou igual a ZERO! ***")
  else:
    x = 1;
x = 0;
while x != 1 :
  nulos = float(input("Entre com o valor dos votos NULOS: "))
  if nulos < 0:
    output.clear()
    print("*** Erro! Digite um numero maior ou igual a ZERO! ***")
  else:
    x = 1;
x = 0;
while x != 1 :
  validos = float(input("Entre com o valor dos votos VALIDOS: "))
  if validos < 0:
    output.clear()
    print("*** Erro! Digite um numero maior ou igual a ZERO! ***")
  else:
    x = 1;
x = 0;
totalVotos = brancos + nulos + validos
percBrancos = (brancos / totalVotos) * 100
percNulos = (nulos / totalVotos) * 100
percValidos = (validos / totalVotos) * 100
print("============================================================")
print("================== Resultado da Eleição ====================")
print("============================================================")
print("Percentual de Votos Brancos: %.2f"% percBrancos,"%")
print("Percentual de Votos Nulos: %.2f"% percNulos,"%")
print("Percentual de Votos Validos: %.2f"% percValidos,"%")
print("Total dos Votos apurados: %d"%totalVotos,"Votos")
print("============================================================")

Entre com o valor dos votos BRANCOS: 47
Entre com o valor dos votos NULOS: 59
Entre com o valor dos votos VALIDOS: 5784
============================================================
================== Resultado da Eleição ====================
============================================================
Percentual de Votos Brancos: 0.80 %
Percentual de Votos Nulos: 1.00 %
Percentual de Votos Validos: 98.20 %
Total dos Votos apurados: 5890 Votos
============================================================

In [ ]:
"""
c.	Leia 2 números e mostre o maior e o menor. 
(Valores inválidos: números menores que -99 e maiores que 99).
"""
from google.colab import output
x = 0;
while x != 1 :
  num1 = int(input("Entre com o valor do 1º Numero: "))
  if num1 < -99 or num1 > 99:
    output.clear()
    print("*** Erro! Digite um numero maior que -99 e menor que 99! ***")
  else:
    x = 1;
x = 0;
while x != 1 :
  num2 = int(input("Entre com o valor do 2º Numero: "))
  if num2 < -99 or num2 > 99:
    output.clear()
    print("*** Erro! Digite um numero maior que -99 e menor que 99! ***")
  else:
    x = 1;
x = 0;
if num1 > num2 :
  print("O numero %d é maior do que o %d" % (num1 , num2))
elif num2 > num1 :
  print("O numero %d é maior do que o %d" % (num2 , num1))
else :
  print("Os numeros digitados sao IGUAIS!")

Entre com o valor do 1º Numero: 0
Entre com o valor do 2º Numero: 0
Os numeros digitados sao IGUAIS!

In [ ]:
#Nivel Médio
"""
a.	leia do teclado uma distância em quilômetros e mostre na tela o seu 
valor convertido em metros. (Valores inválidos: números negativos).
"""
from google.colab import output
x = 0;
while x != 1 :
  distanciaKM = int(input("Entre com o valor da distancia em KM: "))
  if distanciaKM < 0 :
    output.clear()
    print("*** Erro! Digite um numero maior ou igual a ZERO! ***")
  else:
    x = 1;
x = 0;
distanciaMetros = distanciaKM * 1000
print("O valor em metros de %d KM é %d m." % (distanciaKM,distanciaMetros))

*** Erro! Digite um numero maior ou igual a ZERO! ***
Entre com o valor da distancia em KM: 140
O valor em metros de 140 KM é 140000 metros.

In [ ]:
"""
b.	leia do teclado uma distância em metros e mostre na tela o seu valor 
convertido em quilômetros.(Valores inválidos: números negativos).
"""
from google.colab import output
x = 0;
while x != 1 :
  distanciaMT = int(input("Entre com o valor da distancia em Metros: "))
  if distanciaMT < 0 :
    output.clear()
    print("*** Erro! Digite um numero maior ou igual a ZERO! ***")
  else:
    x = 1;
x = 0;
distanciaKM = distanciaMT / 1000
print("O valor em quilometros de %d Metros é %d Km." % (distanciaMT,distanciaKM))

Entre com o valor da distancia em Metros: 140000
O valor em quilometros de 140000 Metros é 140 Km.

In [ ]:
"""
3.	Crie um código utilizando LAÇO WHILE:
a.	Enquanto a1=0 for menor que 5, incrementando 1 a cada laço, mostre na tela o seu número.
"""
a1 = 0;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a1 < 5 :  
  print("O número a1 é = %d"%a1)
  a1+=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a1 in range(5):
  print("O número a1 é = %d"%a1)

==========================================================
WHILE
==========================================================
O número a1 é = 0
O número a1 é = 1
O número a1 é = 2
O número a1 é = 3
O número a1 é = 4
==========================================================
FOR
==========================================================
O número a1 é = 0
O número a1 é = 1
O número a1 é = 2
O número a1 é = 3
O número a1 é = 4

In [ ]:
"""
b.	Enquanto a2=0 for menor que 3, incrementando 1 a cada laço, mostre na tela o seu número multiplicado por 10.
"""
a2 = 0;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a2 < 3 :
  a = a2*3
  print("O número a2 x 3 é = %d"%a)
  a2+=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a2 in range(3):
  a = a2*3
  print("O número a2 x 3 é = %d"%a)

==========================================================
WHILE
==========================================================
O número a2 x 3 é = 0
O número a2 x 3 é = 3
O número a2 x 3 é = 6
==========================================================
FOR
==========================================================
O número a2 x 3 é = 0
O número a2 x 3 é = 3
O número a2 x 3 é = 6

In [ ]:
"""
c.	Enquanto a3=20  for maior que 10, decrementando 1 a cada laço, mostre na tela o seu número.
"""
a3 = 20;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a3 > 10 :
  print("O número a3 é = %d"%a3)
  a3-=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a3 in range(20,10,-1):
  print("O número a3 é = %d"%a3)

==========================================================
WHILE
==========================================================
O número a3 é = 20
O número a3 é = 19
O número a3 é = 18
O número a3 é = 17
O número a3 é = 16
O número a3 é = 15
O número a3 é = 14
O número a3 é = 13
O número a3 é = 12
O número a3 é = 11
==========================================================
FOR
==========================================================
O número a3 é = 20
O número a3 é = 19
O número a3 é = 18
O número a3 é = 17
O número a3 é = 16
O número a3 é = 15
O número a3 é = 14
O número a3 é = 13
O número a3 é = 12
O número a3 é = 11

In [ ]:
"""
d.	Para a4=0 enquanto a4 menor que 10, incrementando 1, mostre na tela o seu número
"""
a4 = 0;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a4 < 10 :
  print("O número a4 é = %d"%a4)
  a4+=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a4 in range(0,10,1):
  print("O número a4 é = %d"%a4)

==========================================================
WHILE
==========================================================
O número a4 é = 0
O número a4 é = 1
O número a4 é = 2
O número a4 é = 3
O número a4 é = 4
O número a4 é = 5
O número a4 é = 6
O número a4 é = 7
O número a4 é = 8
O número a4 é = 9
==========================================================
FOR
==========================================================
O número a4 é = 0
O número a4 é = 1
O número a4 é = 2
O número a4 é = 3
O número a4 é = 4
O número a4 é = 5
O número a4 é = 6
O número a4 é = 7
O número a4 é = 8
O número a4 é = 9

In [ ]:
#Nível Avançado
"""
a.	leia 3 valores (A, B e C) representando as medidas de um triângulo. Mostrar se tais medidas formam um 
triângulo ou não. Lembre-se que o valor de cada lado deve ser menor que a soma dos outros 2 lados e deve 
ser maior que o valor absoluto da diferença entre os outros 2 lados.
| B - C | <  A  < B + C
| A - C | <  B  < A + C
| A - B | <  C  < A + B
"""
A = int(input("Entre com o valor da medida A: "))
B = int(input("Entre com o valor da medida B: "))
C = int(input("Entre com o valor da medida C: "))
print("===================================================")
if A > (B-C) and A < (B+C):
  print("O numero A digitado forma o tringulo!")
else:
  print("O numero A digitado NÃO forma o tringulo!")
if B > (A-C) and B < (A+C):
  print("O numero B digitado forma o tringulo!")
else:
  print("O numero B digitado NÃO forma o tringulo!")
if C > (A-B) and C < (A+B):
  print("O numero C digitado forma o tringulo!")
else:
  print("O numero C digitado NÃO forma o tringulo!")

Entre com o valor da medida A: 2
Entre com o valor da medida B: 4
Entre com o valor da medida C: 5
===================================================
O numero A digitado forma o tringulo!
O numero B digitado forma o tringulo!
O numero C digitado forma o tringulo!

In [ ]:
"""
b.	leia do teclado uma temperatura em graus Fahrenheit e
 mostre na tela o seu valor convertido em Celsius. 
 Lembrando que (c/5) = (f-32)/9. 
 (Valores inválidos: menores que -457,69).
"""
from google.colab import output
x = 0;
while x != 1 :
  gf = int(input("Entre com o valor da temperatura em Fahrenheit: "))
  if gf < -457.69 :
    output.clear()
    print("*** Erro! Digite um numero maior que 457.69ºF ! ***")
  else:
    x = 1;
x = 0;
gc = ((gf-32)/9)*5
print("A temperadura em Celsius é %1.f" % gc,"Graus")

Entre com o valor da temperatura em Fahrenheit: 84
A temperadura em Celsius é 29 Graus

In [ ]:
"""
c.	leia do teclado uma temperatura em graus Celsius e mostre na tela o seu valor 
convertido em Kelvin. Lembrando que 0 grau Kelvin = -273,15 Celsius.
(Valores inválidos: números negativos).
"""
from google.colab import output
x = 0;
while x != 1 :
  gc = int(input("Entre com o valor da temperatura em Celsius: "))
  if gc < 0:
    output.clear()
    print("*** Erro! Digite um numero maior que ZERO ! ***")
  else:
    x = 1;
x = 0;
gk = gc + 273
print("A temperadura em Kelvin é %1.f" % gk,"Graus")

Entre com o valor da temperatura em Celsius: 0
A temperadura em Kelvin é 273 Graus

In [2]:
"""
6.	Crie um código utilizando LAÇO WHILE:
a.	Para a7=0 enquanto a7 menor que 10, incrementando 1, insira um outro while 
aninhado internamente contendo para a8=0 até a8 menor que 10, incrementando 1, 
mostre na tela "(a7,a8)".
"""
a7 = 0;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a7 < 10 :
  a8 = 0;
  while a8 < 10 :
    print("(",a7,",",a8,")")
    a8+=1
  a7+=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a7 in range(0,10,1):
  for a8 in range(0,10,1):
    print("(",a7,",",a8,")")

==========================================================
WHILE
==========================================================
( 0 , 0 )
( 0 , 1 )
( 0 , 2 )
( 0 , 3 )
( 0 , 4 )
( 0 , 5 )
( 0 , 6 )
( 0 , 7 )
( 0 , 8 )
( 0 , 9 )
( 1 , 0 )
( 1 , 1 )
( 1 , 2 )
( 1 , 3 )
( 1 , 4 )
( 1 , 5 )
( 1 , 6 )
( 1 , 7 )
( 1 , 8 )
( 1 , 9 )
( 2 , 0 )
( 2 , 1 )
( 2 , 2 )
( 2 , 3 )
( 2 , 4 )
( 2 , 5 )
( 2 , 6 )
( 2 , 7 )
( 2 , 8 )
( 2 , 9 )
( 3 , 0 )
( 3 , 1 )
( 3 , 2 )
( 3 , 3 )
( 3 , 4 )
( 3 , 5 )
( 3 , 6 )
( 3 , 7 )
( 3 , 8 )
( 3 , 9 )
( 4 , 0 )
( 4 , 1 )
( 4 , 2 )
( 4 , 3 )
( 4 , 4 )
( 4 , 5 )
( 4 , 6 )
( 4 , 7 )
( 4 , 8 )
( 4 , 9 )
( 5 , 0 )
( 5 , 1 )
( 5 , 2 )
( 5 , 3 )
( 5 , 4 )
( 5 , 5 )
( 5 , 6 )
( 5 , 7 )
( 5 , 8 )
( 5 , 9 )
( 6 , 0 )
( 6 , 1 )
( 6 , 2 )
( 6 , 3 )
( 6 , 4 )
( 6 , 5 )
( 6 , 6 )
( 6 , 7 )
( 6 , 8 )
( 6 , 9 )
( 7 , 0 )
( 7 , 1 )
( 7 , 2 )
( 7 , 3 )
( 7 , 4 )
( 7 , 5 )
( 7 , 6 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 8 , 0 )
( 8 , 1 )
( 8 , 2 )
( 8 , 3 )
( 8 , 4 )
( 8 , 5 )
( 8 , 6 )
( 8 , 7 )
( 8 , 8 )
( 8 , 9 )
( 9 , 0 )
( 9 , 1 )
( 9 , 2 )
( 9 , 3 )
( 9 , 4 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 9 , 8 )
( 9 , 9 )
==========================================================
FOR
==========================================================
( 0 , 0 )
( 0 , 1 )
( 0 , 2 )
( 0 , 3 )
( 0 , 4 )
( 0 , 5 )
( 0 , 6 )
( 0 , 7 )
( 0 , 8 )
( 0 , 9 )
( 1 , 0 )
( 1 , 1 )
( 1 , 2 )
( 1 , 3 )
( 1 , 4 )
( 1 , 5 )
( 1 , 6 )
( 1 , 7 )
( 1 , 8 )
( 1 , 9 )
( 2 , 0 )
( 2 , 1 )
( 2 , 2 )
( 2 , 3 )
( 2 , 4 )
( 2 , 5 )
( 2 , 6 )
( 2 , 7 )
( 2 , 8 )
( 2 , 9 )
( 3 , 0 )
( 3 , 1 )
( 3 , 2 )
( 3 , 3 )
( 3 , 4 )
( 3 , 5 )
( 3 , 6 )
( 3 , 7 )
( 3 , 8 )
( 3 , 9 )
( 4 , 0 )
( 4 , 1 )
( 4 , 2 )
( 4 , 3 )
( 4 , 4 )
( 4 , 5 )
( 4 , 6 )
( 4 , 7 )
( 4 , 8 )
( 4 , 9 )
( 5 , 0 )
( 5 , 1 )
( 5 , 2 )
( 5 , 3 )
( 5 , 4 )
( 5 , 5 )
( 5 , 6 )
( 5 , 7 )
( 5 , 8 )
( 5 , 9 )
( 6 , 0 )
( 6 , 1 )
( 6 , 2 )
( 6 , 3 )
( 6 , 4 )
( 6 , 5 )
( 6 , 6 )
( 6 , 7 )
( 6 , 8 )
( 6 , 9 )
( 7 , 0 )
( 7 , 1 )
( 7 , 2 )
( 7 , 3 )
( 7 , 4 )
( 7 , 5 )
( 7 , 6 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 8 , 0 )
( 8 , 1 )
( 8 , 2 )
( 8 , 3 )
( 8 , 4 )
( 8 , 5 )
( 8 , 6 )
( 8 , 7 )
( 8 , 8 )
( 8 , 9 )
( 9 , 0 )
( 9 , 1 )
( 9 , 2 )
( 9 , 3 )
( 9 , 4 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 9 , 8 )
( 9 , 9 )

In [ ]:
"""
b.	Para a6=10 enquanto a6 maior ou igual a 0, decrementando 1, mostre na tela o seu número.
"""
a6 = 10;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a6 >= 0:
  print(a6) 
  a6-=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a6 in range(10,-1,-1):
  print(a6)

==========================================================
WHILE
==========================================================
10
9
8
7
6
5
4
3
2
1
0
==========================================================
FOR
==========================================================
10
9
8
7
6
5
4
3
2
1
0

In [ ]:
"""
c.	Para a5=0 enquanto a5 menor ou igual a 10, incrementando 1, mostre na tela o seu número multiplicado por 10.
"""
a5 = 0;
print("==========================================================")
print("WHILE")
print("==========================================================")
while a5 <= 10:
  print(a5*10) 
  a5+=1
print("==========================================================")
print("FOR")
print("==========================================================")
for a5 in range(11):
  print(a5*10)

==========================================================
WHILE
==========================================================
0
10
20
30
40
50
60
70
80
90
100
==========================================================
FOR
==========================================================
0
10
20
30
40
50
60
70
80
90
100

In [ ]:
"""
8.	Faça um código utilizando qualquer recurso que você aprendeu até agora para:
a.	Mostrar na tela todos os números pares de 0 à 1000
"""
print("Números pares de 0 a 1000")
for par in range(0,1001,1):
  if par % 2 == 0:
    print(par)
print("=========================")

Números pares de 0 a 1000
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526
528
530
532
534
536
538
540
542
544
546
548
550
552
554
556
558
560
562
564
566
568
570
572
574
576
578
580
582
584
586
588
590
592
594
596
598
600
602
604
606
608
610
612
614
616
618
620
622
624
626
628
630
632
634
636
638
640
642
644
646
648
650
652
654
656
658
660
662
664
666
668
670
672
674
676
678
680
682
684
686
688
690
692
694
696
698
700
702
704
706
708
710
712
714
716
718
720
722
724
726
728
730
732
734
736
738
740
742
744
746
748
750
752
754
756
758
760
762
764
766
768
770
772
774
776
778
780
782
784
786
788
790
792
794
796
798
800
802
804
806
808
810
812
814
816
818
820
822
824
826
828
830
832
834
836
838
840
842
844
846
848
850
852
854
856
858
860
862
864
866
868
870
872
874
876
878
880
882
884
886
888
890
892
894
896
898
900
902
904
906
908
910
912
914
916
918
920
922
924
926
928
930
932
934
936
938
940
942
944
946
948
950
952
954
956
958
960
962
964
966
968
970
972
974
976
978
980
982
984
986
988
990
992
994
996
998
1000
=========================

In [ ]:
"""
8.	Faça um código utilizando qualquer recurso que você aprendeu até agora para:
b.	Mostrar na tela todos os números ímpares de 5 à 55
"""
print("Números impares de 5 a 55")
for impar in range(5,56,1):
  if impar % 2 != 0:
    print(impar)
print("=========================")

Números impares de 5 a 55
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
=========================

In [ ]:
"""
8.	Faça um código utilizando qualquer recurso que você aprendeu até agora para:
c.	Mostrar na tela somente números primos de 2 à 100;
"""
print("Números PRIMOS de 2 a 100")
for i in range(2, 101): 
  if i>1: 
    for j in range(2,i): 
        if(i % j==0): 
            break
    else: 
        print(i) 
print("=========================")

Números PRIMOS de 2 a 100
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
=========================